using System.ComponentModel;
using ModelContextProtocol.Server;

namespace AzureMissionWorkspace.McpServer.Prompts;

/// <summary>
/// MCP prompts that guide the conversational workflow described in the product vision. Prompts
/// only shape the conversation; they never grant authorization, approve requests, or trigger a
/// deployment on their own -- every mutating step still goes through the corresponding MCP tool,
/// which enforces its own server-side authorization.
/// </summary>
[McpServerPromptType]
public sealed class MissionWorkspacePrompts
{
    [McpServerPrompt(Name = "start_deployment_request")]
    [Description("Guides a user unfamiliar with Azure through describing a desired capability and starting a governed deployment request.")]
    public static string StartDeploymentRequest(
        [Description("A short description of what the user wants to accomplish, in their own words.")] string userGoal) => $"""
        You are helping a user who is unfamiliar with Azure request an approved Azure capability
        through Azure Mission Workspace. The user's goal, in their own words, is:

        "{userGoal}"

        Follow this governed workflow -- do not skip steps or invent capabilities outside the
        approved catalog:

        1. Call `recommend_service_pattern` with a natural-language description of the goal and the
           target `environmentProfileId` to get scored, approved candidate service patterns.
        2. Present the top candidates to the user and ask them to explicitly select or reject one.
           Never auto-select a pattern on the user's behalf.
        3. Call `create_deployment_request` to start a draft, then `select_service_pattern` once the
           user confirms their choice.
        4. Call `get_required_inputs` for the selected pattern and ask the user, one at a time, for
           any required inputs that are still missing. Never ask for or accept secret values --
           secrets must be referenced by Key Vault identifier or pipeline secret variable only.
        5. Call `update_deployment_request` with the collected, non-secret parameter values.
        6. Explain to the user that validation, an ARM what-if plan, policy evaluation, and human
           approval will happen next, and that you cannot deploy anything yourself.
        """;

    [McpServerPrompt(Name = "explain_deployment_plan")]
    [Description("Explains a deterministic, normalized deployment plan to a non-expert user in plain language.")]
    public static string ExplainDeploymentPlan(
        [Description("The deployment request id whose plan should be explained.")] string deploymentRequestId) => $"""
        Call `get_deployment_plan` with deploymentRequestId '{deploymentRequestId}' to retrieve the
        deterministic, normalized deployment plan. Then call `explain_deployment_plan` to obtain a
        generated natural-language summary.

        When presenting the result to the user:
        - Clearly separate the deterministic findings (change type, resource, and risk, which are
          authoritative and never generated by you) from the generated explanation (which only
          summarizes, and can never override, the deterministic result).
        - Call out any Delete, Replace, or Unknown changes explicitly, since these carry elevated
          risk and review requirements.
        - Remind the user that approval, not this conversation, is what authorizes the change.
        """;

    [McpServerPrompt(Name = "resolve_policy_findings")]
    [Description("Helps a user understand and remediate deterministic policy findings for a deployment request.")]
    public static string ResolvePolicyFindings(
        [Description("The deployment request id whose policy findings should be resolved.")] string deploymentRequestId) => $"""
        Call `get_policy_findings` with deploymentRequestId '{deploymentRequestId}'. For each
        blocking finding, call `explain_policy_finding` with its ruleId to obtain a plain-language
        explanation and remediation guidance.

        Never suggest bypassing, overriding, or disabling a policy finding. If a finding genuinely
        should not apply, tell the user that only an authorized platform administrator can grant a
        time-limited, auditable policy exception outside of this conversation -- you cannot grant
        one yourself, and there is no tool available to bypass policy.
        """;

    [McpServerPrompt(Name = "troubleshoot_failed_deployment")]
    [Description("Helps a user understand why a deployment request failed validation, policy evaluation, approval, or pipeline execution.")]
    public static string TroubleshootFailedDeployment(
        [Description("The deployment request id that failed.")] string deploymentRequestId) => $"""
        Call `get_deployment_request` with deploymentRequestId '{deploymentRequestId}' and inspect
        its status. Depending on the status:

        - ValidationFailed: call `validate_deployment_request` results/diagnostics already returned,
          and explain the Bicep compile/lint/template-validation errors in plain language. Do not
          attempt to author or suggest arbitrary Bicep changes yourself -- only the pattern owner can
          change the approved module.
        - Rejected: call `get_deployment_request` to see the current state, and explain that a
          human approver rejected the request; the user should revise the request and resubmit.
        - DeploymentFailed: call `get_deployment_status` and, if available, `get_deployment_evidence`
          to review the pipeline execution outcome, and explain the failure without exposing secret
          values or raw pipeline logs verbatim.

        Always remind the user that only the Azure DevOps pipeline executes deployments, and that
        destructive deployments are never automatically retried.
        """;
}
