using System.Text;
using AzureMissionWorkspace.Application.Abstractions.Bicep;
using AzureMissionWorkspace.Domain.Entities;

namespace AzureMissionWorkspace.ServicePatterns.Rendering;

/// <summary>
/// Deterministically renders a <c>.bicepparam</c> artifact from a service pattern's declared
/// inputs, the requestor-supplied (non-secret) parameter values, and environment-profile-controlled
/// platform values. Secret inputs are always rendered as Key Vault secret references, never as
/// literal values.
/// </summary>
public sealed class DeterministicBicepParameterRenderer : IBicepParameterRenderer
{
    public Task<string> RenderAsync(ServicePattern pattern, DeploymentRequest request, EnvironmentProfile environmentProfile, CancellationToken cancellationToken = default)
    {
        if (request.Parameters is null)
        {
            throw new InvalidOperationException("The deployment request has no parameters to render.");
        }

        var builder = new StringBuilder();
        builder.AppendLine("// Auto-generated by AzureMissionWorkspace.ServicePatterns.DeterministicBicepParameterRenderer.");
        builder.AppendLine("// Do not edit by hand -- this file is regenerated deterministically from the deployment request.");
        builder.AppendLine("using 'main.bicep'");
        builder.AppendLine();

        foreach (var input in pattern.RequiredInputs.OrderBy(i => i.Name, StringComparer.Ordinal))
        {
            if (!request.Parameters.TryGetValue(input.Name, out var value) || value is null)
            {
                throw new InvalidOperationException($"Missing required input '{input.Name}' during parameter rendering.");
            }

            builder.AppendLine($"param {input.Name} = {FormatValue(input.Type, value)}");
        }

        foreach (var input in pattern.OptionalInputs.OrderBy(i => i.Name, StringComparer.Ordinal))
        {
            if (request.Parameters.TryGetValue(input.Name, out var value) && value is not null)
            {
                builder.AppendLine($"param {input.Name} = {FormatValue(input.Type, value)}");
            }
        }

        foreach (var secretName in pattern.SecretInputs.OrderBy(n => n, StringComparer.Ordinal))
        {
            // Secret values are never written to the parameter file. Reference a pipeline secret
            // variable name instead; the value itself is resolved at deployment time from Key
            // Vault or a secret pipeline variable group.
            builder.AppendLine($"param {secretName} = readEnvironmentVariable('{secretName.ToUpperInvariant()}_SECRET_REF', '')");
        }

        foreach (var (tagName, tagValue) in environmentProfile.RequiredTags.OrderBy(t => t.Key, StringComparer.Ordinal))
        {
            builder.AppendLine($"// required tag '{tagName}' enforced by environment profile: {tagValue}");
        }

        return Task.FromResult(builder.ToString());
    }

    private static string FormatValue(string type, string value)
    {
        return type.ToLowerInvariant() switch
        {
            "boolean" => value.ToLowerInvariant(),
            "integer" or "number" => value,
            "array" or "object" => value,
            _ => $"'{value.Replace("'", "\\'")}'",
        };
    }
}
